# -*- coding: utf-8 -*-
"""movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tiEXf56l5q37GzfusXzU0sqruqe0W30
"""

import pandas as  pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('movies_metadata.csv')
df.head()

df.columns

df.info()

df.shape

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates().reset_index(drop=True)

df.info()

df = df[['title','overview','genres','vote_average','popularity','tagline']]

df.head(3)

df = df.dropna(subset = ['title'])

df.isnull().sum()

df['overview'] =df['overview'].fillna('')

df.isnull().sum()

df.iloc[0]['genres']

df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in x]))

df.head(3)

df['tagline'] = df['tagline'].fillna('')

df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline']

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'[\W_]', ' ', text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words] # Remove stop words
    tokens = [lemmatizer.lemmatize(word) for word in tokens] # Lemmatization
    return " ".join(tokens) #tokenizations

df['tags'] = df['tags'].apply(preprocess_text)

df['tags'][0]

df = df.reset_index(drop=True)

indices = pd.Series(df.index, index=df['title']).drop_duplicates()

indices

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

tfidf_matrix = tfidf.fit_transform(df['tags'])

tfidf_matrix

def recommended(title, n =10):
  if title not in indices:
    return "Movie not found in the dataset"
  idx = indices[title]
  similarity_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  movie_indices = similarity_scores.argsort()[::-1][1:n+1]
  return df['title'].iloc[movie_indices]

recommended('The Dark Knight Rises')

import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))


pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))

